// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $App from "./islands/App.tsx";
import * as $Graph from "./islands/Graph.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/App.tsx": $App,
    "./islands/Graph.tsx": $Graph,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
